[tool.poetry]
name = "kCAS"
version = "0.1.0"
description = ""
authors = ["ynx0"]

[tool.poetry.dependencies]
python = "^3.9"
lark = "^1.1.2"

[tool.poetry.dev-dependencies]
ipython = "^8.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
